### ISSUE TITLE
Service.Name not set correctly for Jobs

### ISSUE THREAD

**Issue by OllieDavies** [newrelic-experimental/gitlab#11]
GitLab Jobs exported via `new-relic-metrics-exporter` all contain the string "gitlab-exporter" in `Service.Name` instead of being the project name.

Looks like [`get_jobs`](https://github.com/newrelic-experimental/gitlab/blob/main/new-relic-metrics-exporter/get_resources.py#L248-L252) never overrides `GLAB_SERVICE_NAME` like other methods in `get_resources.py` do.

Happy to raise a PR if preferred 🙂

**Comment by dpacheconr** [comment]
fixed in 1.03
thanks for reporting @OllieDavies

**Comment by OllieDavies** [comment]
That's fixed it, thanks @dpacheconr 🎉
