### ISSUE TITLE
Logs incorrectly reported as errors

### ISSUE THREAD

**Issue by jlirochon** [newrelic-experimental/gitlab#14]
For example my logs containing the string `export WARNING_AS_ERROR='True'` are incorrectly flagged by [this code](https://github.com/newrelic-experimental/gitlab/blob/73222c9c521f882f9024de805cbc1983c99bffff/new-relic-exporter/exporter.py#L135)

**Comment by dpacheconr** [comment]
@jlirochon thanks for reporting, this should be fixed in 1.0.5, which also includes your PR for the logs variable
https://github.com/newrelic-experimental/gitlab/releases/tag/1.0.5
Thanks
