### ISSUE TITLE
Span length limited to 60 minutes

### ISSUE THREAD

**Issue by XC-** [newrelic-experimental/gitlab#15]
We were requested to open up a ticket on this here.

In our project, we would like to export data of our pipelines and jobs to New Relic. We are using a custom solution based on Gitlab CI webhooks that sends data in opentelemetry format. The problem is, as the top span is the pipeline itself and it contains multiple job that run at various points of time leading very often to a pipeline that has "ended" possibly even days later, thus creating a pipeline span that would have length of several days. At the moment this is not possible due to the limitation imposed by the New Relic's opentelemetry intake.

Some possible scenarios:

Scenario A: 
- Pipeline is created
- First job is run immediately
- The next job is a manual step that is run three days later
- Pipeline is completed after the manual step is complete and total length of the pipeline is several days

Scenario B: 
- Pipeline is created
- A job fails (perhaps due to some external issue)
- Fix happens the next day and the pipeline is retried
- Pipeline is completed again, but now as a successful pipeline with total length of hours or over a day

Scenario C: 
- Pipeline is created
- Most of the jobs are run successfully right away
- A test job takes over an hour to complete (this could be some analysis job as well)
- A job span is created with length of over an hour and is rejected because of it

The pipeline length could provide visibility on certain lead times and even if that is circumvented somehow, there is the case of jobs being longer than an hour (which is quite realistic scenario for e.g. analysis jobs, test jobs, some larger builds that are run as nightly jobs).

**Comment by dpacheconr** [comment]
Hi @XC- are you actually using the integration provided in this repo or you using our own custom open-telemetry integration?

If you using this integration, we can possibly manually calculate span start time based on duration and end time, instead of using gitlab provided start time ( which is first time pipeline ran not the time attempt was run )
This should cover most of your use cases ( will need testing ) 
From back of my mind, the one to watch out for, that requires investigation, is the one with duration over 1 hour. Which is  covered in NR docs https://docs.newrelic.com/docs/distributed-tracing/troubleshooting/missing-trace-data/#late-spans

**Comment by XC-** [comment]
Hi @dpacheconr , this is a partially a mixup on my end on what the real problem is, so to clarify:
It is possible to send spans longer than 1 hour to new relic, but not if the start time is more than 1 hour in the past.

We are using our own implementation for sending opentelemetry data to newrelic, so not the one in this repository. Basically, we are trying to add the data to new relic when the pipeline completes and webhook sends data to our service about the pipeline completion. This is based on a standard Gitlab webhook. From the data, we are parsing the start and end times etc.

But the problem is still there. The span start can be further in the past than the 1 hour limit.

Is there some workaround for this? Is it possible to send a span start and end separately, and define the trace id ourselves, so that we could complete the spans in parts?

**Comment by dpacheconr** [comment]
Yes, spans must be sent within the last sixty minutes to be captured in a trace index ( to show in trace UI ). The only way currently that I know off, is to send spans x interval of time until trace finishes. I imagine you are parsing the data after the event occurred, i.e. after the pipeline finishes, so you can't create the span every x minutes and not reach the  60 minutes limit. If gitlab webhook provides in progress events, then maybe you can, depending how frequent they are sent.
I am closing this issue as this is not related to exporters provided in this repo.
