### ISSUE TITLE
Change of time format possible?

### ISSUE THREAD

**Issue by magicofit** [newrelic-experimental/gitlab#16]
Hi,

i would like to calculate with datetimes inside NRQL:

is it possible, to change format of:
-commit.authored_date
-commit.committed_date
-commit.created_at
-finished_at
-pipeline.created_at
-pipeline.updated_at
-started_at
ect.

to unix-timestamps?
than it would be easier to write custom durations inside NR between this values.

Thanks!

**Comment by dpacheconr** [comment]
Let me have look what can be done and get back to you
