### ISSUE TITLE
Failure to export logs, Permission Denied

### ISSUE THREAD

**Issue by jared-hess** [newrelic-experimental/gitlab#17]
I've set up the integration in one of my projects according to the following document:
https://newrelic.com/blog/how-to-relic/monitor-gitlab-with-opentelemetry#toc-setting-up-the-new-relic-metrics-exporter

The child pipeline gets triggered, and the pipeline runs successfully but I don't see any data in New Relic. I see the following logs in the pipeline job log:

```
2023-06-01 20:25:40,185 ERROR [opentelemetry.exporter.otlp.proto.grpc.exporter] [exporter.py:375] [trace_id=0 span_id=0 resource.service.name=] - Failed to export logs, error code: StatusCode.PERMISSION_DENIED
```
I am using version 1.0.6

**Comment by dpacheconr** [comment]
Please double check your license key, ensure you are using New Relic Ingest license key

**Comment by jared-hess** [comment]
Yep, that was it, my bad! Thanks for the help.
