### ISSUE TITLE
GitLab integration with newrelic

### ISSUE THREAD

**Issue by devpv-ram** [newrelic-experimental/gitlab#20]
I configured all the environment variables and also configured the exporters which are mentioned in the [blog](https://newrelic.com/blog/how-to-relic/monitor-gitlab-with-opentelemetry) but still I didn't get any data on my NewRelic UI.

![Screenshot 2023-08-02 at 11 16 02 AM](https://github.com/newrelic-experimental/gitlab/assets/84476911/7f1cdc88-a766-4bcf-9625-77fc37c530a6)
![Screenshot 2023-08-02 at 11 24 57 AM](https://github.com/newrelic-experimental/gitlab/assets/84476911/703a8e7b-bb9e-4813-be44-b38d6b986864)
![Screenshot 2023-08-02 at 11 26 44 AM](https://github.com/newrelic-experimental/gitlab/assets/84476911/fa45809a-4794-40b2-9c86-dcf185173dd7)

**Comment by devpv-ram** [comment]
Updated the exporter to run with Docker executor. Still nothing on newrelic side

<img width="703" alt="Screenshot 2023-08-03 at 12 02 04 PM" src="https://github.com/newrelic-experimental/gitlab/assets/84476911/8fcca609-73e9-48ca-b883-ddbd84775237">

**Comment by dpacheconr** [comment]
Hi

After line 11 on your screenshot what do you get?

I would expect some errors or something similar to
[image: image.png]

Have you double checked you using the license/ingest api and it's correctly
set no spaces before or after?

Are you using a personal gitlab token or group token?

Regards
--
*Diogo Pacheco*
*Senior Solutions Architect *
*EMEA Field Engineering Team*
*www.newrelic.com <http://www.newrelic.com>*

**Comment by devpv-ram** [comment]
The pipeline ran successfully without any errors.

I'm using a personal gitlab token

<img width="703" alt="Screenshot 2023-08-03 at 12 16 52 PM" src="https://github.com/newrelic-experimental/gitlab/assets/84476911/ff3fde42-5fcb-4256-843d-af26b183f330">

**Comment by devpv-ram** [comment]
I'm using these variables.

    GLAB_TOKEN: $GLAB_TOKEN
    NEW_RELIC_API_KEY: $NEW_RELIC_API_KEY
    GLAB_EXPORT_PROJECTS_REGEX: ".*"
    GLAB_EXPORT_GROUPS_REGEX: ".*"

**Comment by dpacheconr** [comment]
Hi

Remove GLAB_EXPORT_GROUPS_REGEX: ".*" and GLAB_EXPORT_PROJECTS_REGEX: ".*"
and try again.

This will allow it to run with all default values.

Let us know if that works

Regards
--
*Diogo Pacheco*
*Senior Solutions Architect *
*EMEA Field Engineering Team*
*www.newrelic.com <http://www.newrelic.com>*

**Comment by devpv-ram** [comment]
Pipeline ran successfully after removing those variables. Still nothing exported to newrelic dashboard

> Created fresh repository.
> Checking out 556b17e8 as detached HEAD (ref is SRE-159)...
> Skipping Git submodules setup
> $ git remote set-url origin "${CI_REPOSITORY_URL}"
> Executing "step_script" stage of the job script
> 00:02
> Using docker image sha256:e46e8a7013e[18](https://gitlab.com/propertyvista/devops/gitlab-repo-management/-/jobs/4800506139#L18)f5e2557dab7559e5f9f91007211f0beda33159701f68404588e for docker.io/dpacheconr/gitlab-metrics-exporter:1.0.6 with digest dpacheconr/gitlab-metrics-exporter@sha256:802d8efd4c80e6d4f1a14[19](https://gitlab.com/propertyvista/devops/gitlab-repo-management/-/jobs/4800506139#L19)c5a9cab2ddf8dc44d83bec8a10352abb7546a44a8 ...
> Found total of 0 projects using -> OWNED: True and VISIBILITY: private. 
> Checking which ones match provided paths and project regex configuration
> Nothing to export check your configuration!!!
> Cleaning up project directory and file based variables
> 00:01
> Job

**Comment by dpacheconr** [comment]
You won’t see anything because logs are saying the projects you have are not owned.

If you look at the line owned and visibility it says it can’t find any owned projects with visibility private.

You will need to check your projects configuration and amend these variables according to your setup

Happy to setup call to discuss this further if you wish

Regards
Diogo

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by devpv-ram** [comment]
Please send me a link to your calendar to schedule a call. Thank you.

**Comment by dpacheconr** [comment]
Hi

I am available Wednesday 12pm-4pm UK time.

Let me know if that works for you and what email shall I send the invite to.

Regards
--
*Diogo Pacheco*
*Senior Solutions Architect *
*EMEA Field Engineering Team*
*www.newrelic.com <http://www.newrelic.com>*

**Comment by devpv-ram** [comment]
Hi. Can we schedule the call for 3 p.m UK time / 10 a.m ET.
Please send me the invite on rsakineti@propertyvista.com
Thank you!

**Comment by dpacheconr** [comment]
I sent you an invite.
Regards
--
*Diogo Pacheco*
*Senior Solutions Architect *
*EMEA Field Engineering Team*
*www.newrelic.com <http://www.newrelic.com>*
