### ISSUE TITLE
Entire pipeline's jobs exported when only one is updated

### ISSUE THREAD

**Issue by Blinko26** [newrelic-experimental/gitlab#27]
Hi,

When a job is retrying then all the jobs in the pipeline are exported again even if the job had run 2 weeks ago.

It would be better if a check was added to each job to avoid export job multiple time.

Or is this the intended behavior ?

**Comment by dpacheconr** [comment]
thanks for contributing with PR https://github.com/newrelic-experimental/gitlab/pull/28
exporting just the ran job in last configured minutes, causes the traces to show only one job/step/span when in reality more jobs had ran before for that pipeline
let's implement this feature for now and see if there is any feedback from other users, we can always revert changes or make this configurable so suits everyone
