### ISSUE TITLE
Less data from gitlab to new relic by default?

### ISSUE THREAD

**Issue by magicofit** [newrelic-experimental/gitlab#4]
Hi,

i have here a usecase description

- We have in our gitlab lets say >800 projects 
- Only for projects inside 30 groups the gitlab-pipeline-monitoring to new relic is relevant
- Every team use in different projects different environment-key-names (with sensible content?)

Maybe its a documentation issue, but i have the feeling, that the variables doesnt fit for this usecase.
I cant say, what i want to "DROP", but i can say, what i want explicitly to "EXPORT" in our company.

I need a different paradigm to convince my boss, that pipeline monitoring with this tool is a good idea.
First i want to start with one project no env-variables, less attributes, logs ect. and if we understand the security&performance impact, than slowly grow (same process we have done with the NR-Agents). 
At start maybe a "GLAB_EXPORT_ENVS"-variable is a good idea, so that i can set it to FALSE prevent transfer of any global/group/project-ENVs to new relic.

**Comment by dpacheconr** [comment]
You should now be able to set GLAB_LOW_DATA_MODE and only export the bear minimum information to NR 
https://github.com/newrelic-experimental/gitlab/releases/tag/1.0.1
